name: sugar-ai
version: '3.8'
services:
  sugar-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:8000"
    command: ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
